version: "3.4"
services:
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db-api:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    networks:
      - beansPokemons
  frontend:
    build: 
      context: ./frontend
    entrypoint: /bin/sh
    ports:
      - 5173:5173
    networks:
      - beansPokemons
  backend:
    build:
      context: ./backend
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - beansPokemons