version: "3.4"
services:
  database:
    image: postgres:alpine
    network_mode: host
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db-api:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

  frontend:
    environment:
      URL_POKE_API_WEB: https://pokeapi.co/api/v2
      URL_BASE_API: http://127.0.0.1:3000
    build:
      context: ./frontend
    network_mode: host
    ports:
      - 5173:5173
    restart: always

  backend:
    environment:
      DATABASE_URL: "postgresql://pguser:pgpassword@database:5432/pokedex?schema=public"
      JWT_SECRET: "POKEMON"
      POKE_URL: "https://pokeapi.co/api/v2"
    build:
      context: ./backend
    network_mode: host
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - database