FROM node:20
WORKDIR /srv/app
COPY package.json ./
COPY prisma/schema.prisma ./prisma/
RUN npm install
COPY . .
EXPOSE 3000
CMD ["bash", "-c", "npx prisma migrate deploy && npx prisma generate && npm run dev"]